apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::915435967765:role/eksctl-eksClusterJwt-nodegroup-ng-NodeInstanceRole-WG7K0EW941UI
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::915435967765:role/eksDeployRole
      username: build
      groups:
        - system:masters
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
